name: soccer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  provider:
  scribble: ^0.4.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  http: ^0.13.4
  html: ^0.15.0
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0
  date_field: ^3.0.1
  syncfusion_flutter_sliders: ^20.1.58
  syncfusion_flutter_calendar: ^20.1.58
  numberpicker: ^2.1.1
  draggable_fab: ^0.1.4
  flutter_screenutil: ^5.5.3+2
  change_app_package_name: ^1.0.0
  flutter_material_pickers: ^3.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - image/titleBackgroundImage.png
    - image/profileImage.png
    - image/googleIcon.png
    - image/underplayLogo.png
    - image/pain.png
    - image/footballplayground.png
    - image/MatchField.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: font/Pacifico.ttf
          weight: 400
